spring:
  activemq:
    broker-url: failover:(tcp://lesbamqd01.lx.finbel.intra:61616,tcp://lesbamqd02.lx.finbel.intra:61616,tcp://lesbamqd03.lx.finbel.intra:61616,tcp://lesbamqd04.lx.finbel.intra:61616)?initialReconnectDelay=100&jms.watchTopicAdvisories=false
    user: ecsapp
    password : (ecsapp2023)
    in-memory: false
    pool:
      enabled: false

ccngateway:
  generator:
    application: ecs-ieca
    queue:
      toeurope: "VirtualTopic.ccncsi.toEurope"
      fromeurope: "ecs.ccncsi.fromEurope"