spring:
  activemq:
    broker-url: failover:(tcp://lesbamqd01.lx.finbel.intra:61616,tcp://lesbamqd02.lx.finbel.intra:61616,tcp://lesbamqd03.lx.finbel.intra:61616,tcp://lesbamqd04.lx.finbel.intra:61616,tcp://lesbamqd05.lx.finbel.intra:61616,tcp://lesbamqd06.lx.finbel.intra:61616)
    user: cdmrapp
    password : (cdmrapp2023)
    in-memory: false
    pool:
      enabled: false

ccngateway:
  generator:
    application: ecs-ieca
    queue:
      toeurope: "VirtualTopic.ccncsi.toEurope"
      fromeurope: "ecs.ccncsi.fromEurope"
      fromieca: "ecs.ieca.ccncsi.fromEurope"