spring:
  activemq:
    broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
    user: admin
    password : admin
    in-memory: false
    pool:
      enabled: false

ccngateway:
  generator:
    application: ncts
    queue:
      toeurope: "VirtualTopic.ccncsi.toEurope"
      fromeurope: "ncts.ccncsi.fromEurope"